import zipfile
import os
import sys
import argparse
from pathlib import PurePath

cmd = argparse.ArgumentParser(prog='ZipChar',
                        description='dump Zip filenames to a C string array')
cmd.add_argument("-f", "--file", help="Path to the *.zip|*.kpf file to be processed", required=True)
cmd.add_argument("-p", "--pattern", help="What pattern (subdir/file-prefix) to filter for?", required=False)
cmd.add_argument("-e", "--ext", help="File extension to filter results by", required=True)
args = cmd.parse_args()

# non-regex version

if not os.path.exists(args.file):
    print(f"'{args.file}' does not exist!", file=sys.stderr)
    sys.exit(1)

if not args.file.endswith(('.zip', '.kpf')):
    print(f"Input file must be .zip or .kpf!", file=sys.stderr)
    sys.exit(1)

# splits stored here
directories = []
filenames = []
extensions = []

with zipfile.ZipFile(args.file, 'r') as zip: # you should avoid redefining `zip`, since `zip()` is built-in
    for path in zip.namelist():
        # use pathlib.PurePath to parse paths instead
        path_obj = PurePath(path)

        file_part = path_obj.stem  # filename without extension
        ext_part = path_obj.suffix  # extension

        if path_obj.parent == PurePath('.'):
            dir_part = ''  # root-level file
        else:
            dir_part = str(path_obj.parent) + '/'

        # skip if this is a directory entry
        if not file_part and not ext_part:
            continue

        # filter based on CLI args
        # check if directory starts with the pattern
        if args.pattern and not dir_part.startswith(args.pattern):
            continue

        # case-insensitive, handle with or without dot
        ext_normalized = ext_part.lstrip('.').lower()
        args_ext_normalized = args.ext.lstrip('.').lower()
        if ext_normalized != args_ext_normalized:
            continue

        # compose lists
        directories.append(dir_part)
        filenames.append(file_part)
        extensions.append(ext_part)

    if not filenames:
        print("No matches found!", file=sys.stderr)
        sys.exit(1)

    print("// generated by ZipChar")
    print("static const char *str[] = {")
    
    for i, filename in enumerate(filenames):
        comma = "," if i < len(filenames) - 1 else ""
        print(f'    "{filename}{extensions[i]}"{comma}')
    
    print("};")