import zipfile
import os
import sys
import argparse

cmd = argparse.ArgumentParser(prog='ZipChar',
                        description='dump Zip filenames to a C string array')
cmd.add_argument("-f", "--file", help="Path to the *.zip|*.kpf file to be processed", required=True)
cmd.add_argument("-p", "--pattern", help="What pattern (subdir/file-prefix) to filter for?", required=False)
cmd.add_argument("-e", "--ext", help="File extension to filter results by", required=True)
args = cmd.parse_args()

if not os.path.exists(args.file):
    print(f"'{args.file}' does not exist!", file=sys.stderr)
    sys.exit(1)

extension = os.path.splitext(args.file)[1]
if not (extension == ".zip" or extension == ".kpf"):
    print(f"Input extension {extension} is invalid!", file=sys.stderr)
    sys.exit(1)

with zipfile.ZipFile(args.file, 'r') as zip:
    if(args.pattern):
        paths = [path for path in zip.namelist() if path.startswith(args.pattern) and path.endswith(args.ext)]
    else:
        paths = [path for path in zip.namelist() if path.endswith(args.ext)]

    print(zip.namelist())

    if not paths:
        print("No matches found!", file=sys.stderr)
        sys.exit(1)

    print("// generated by ZipChar")
    print("static const char *str[] = {")

    for idx, path in enumerate(paths):
        if idx == len(paths) - 1:
            print(f"    \"/{path}\"")
        else:
            print(f"    \"/{path}\",")

    print("};")